In [5]:
import numpy as np
import matplotlib as plt
import math
%matplotlib inline

In [36]:
R_naught = 2
contagious_period = 5
average_transmissions_per_day = R_naught / contagious_period
death_rate = 0.01
population = 1000000
period = 100
print(average_transmissions_per_day)

0.4


In [37]:
new = np.zeros(period, dtype=np.int64)
active = np.zeros(period, dtype=np.int64)
recovered = np.zeros(period, dtype=np.int64)
total_cases = np.zeros(period,dtype=np.int64)
deaths = np.zeros(period,dtype=np.int64)
total_deaths = np.zeros(period, dtype=np.int64)
new[0] = 1
active[0] = 1
total_cases[0] = 1

In [38]:
for day in range(1,period):
    for person in range(active[day-1]):
        transmit = np.random.random()
        if transmit <= average_transmissions_per_day: 
            failed_transmit = np.random.random()
            immune_rate = (sum(recovered) + total_deaths[day - 1])/(population - total_deaths[day - 1]+1)
            if failed_transmit >= immune_rate:
                new[day] += 1
            if np.random.random() <= death_rate:
                deaths[day] += 1
        if day >= contagious_period:
            recovered[day] = new[day - contagious_period]
    active[day] = active[day - 1] + new[day] - recovered[day] - deaths[day]
    total_cases[day] = total_cases[day - 1] + new[day]
    total_deaths[day] = total_deaths[day - 1] + deaths[day]
            

In [39]:
new

array([     1,      1,      2,      0,      1,      4,      3,      4,
            4,      9,      8,      9,     12,     18,     24,     31,
           41,     51,     65,     84,    107,    130,    158,    192,
          269,    347,    449,    550,    735,    926,   1213,   1495,
         1872,   2414,   3156,   3920,   5102,   6329,   8151,  10191,
        12953,  16475,  20635,  25835,  32328,  39815,  49105,  59008,
        70879,  82600,  94374, 105229, 111034, 111966, 103795,  87630,
        64131,  37316,  12750,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0], dtype=int64)

In [40]:
active

array([     1,      2,      4,      4,      5,      8,     10,     12,
           16,     24,     28,     32,     40,     53,     68,     91,
          123,    161,    207,    266,    340,    427,    534,    660,
          843,   1081,   1397,   1784,   2319,   2969,   3822,   4860,
         6159,   7814,  10012,  12674,  16224,  20619,  26263,  33185,
        42100,  53283,  67395,  84805, 106614, 133056, 165146, 202887,
       247117, 296406, 349806, 404519, 454924, 494179, 513474, 504656,
       461617, 386077, 285268, 180359,  92014,  27519,  -9904,  -9904,
        -9904,  -9904,  -9904,  -9904,  -9904,  -9904,  -9904,  -9904,
        -9904,  -9904,  -9904,  -9904,  -9904,  -9904,  -9904,  -9904,
        -9904,  -9904,  -9904,  -9904,  -9904,  -9904,  -9904,  -9904,
        -9904,  -9904,  -9904,  -9904,  -9904,  -9904,  -9904,  -9904,
        -9904,  -9904,  -9904,  -9904], dtype=int64)

In [41]:
total_cases

array([      1,       2,       4,       4,       5,       9,      12,
            16,      20,      29,      37,      46,      58,      76,
           100,     131,     172,     223,     288,     372,     479,
           609,     767,     959,    1228,    1575,    2024,    2574,
          3309,    4235,    5448,    6943,    8815,   11229,   14385,
         18305,   23407,   29736,   37887,   48078,   61031,   77506,
         98141,  123976,  156304,  196119,  245224,  304232,  375111,
        457711,  552085,  657314,  768348,  880314,  984109, 1071739,
       1135870, 1173186, 1185936, 1185936, 1185936, 1185936, 1185936,
       1185936, 1185936, 1185936, 1185936, 1185936, 1185936, 1185936,
       1185936, 1185936, 1185936, 1185936, 1185936, 1185936, 1185936,
       1185936, 1185936, 1185936, 1185936, 1185936, 1185936, 1185936,
       1185936, 1185936, 1185936, 1185936, 1185936, 1185936, 1185936,
       1185936, 1185936, 1185936, 1185936, 1185936, 1185936, 1185936,
       1185936, 1185

In [42]:
total_deaths

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     2,     2,     3,     3,     3,     3,     4,
           5,     6,     8,    10,    10,    11,    13,    15,    18,
          23,    31,    38,    51,    59,    82,   106,   138,   183,
         240,   302,   395,   508,   626,   816,  1010,  1284,  1612,
        2032,  2572,  3204,  4018,  5001,  6160,  7571,  9192, 11024,
       12924, 14998, 16939, 18761, 20354, 21468, 22183, 22547, 22654,
       22654, 22654, 22654, 22654, 22654, 22654, 22654, 22654, 22654,
       22654, 22654, 22654, 22654, 22654, 22654, 22654, 22654, 22654,
       22654, 22654, 22654, 22654, 22654, 22654, 22654, 22654, 22654,
       22654, 22654, 22654, 22654, 22654, 22654, 22654, 22654, 22654,
       22654], dtype=int64)

In [43]:
recovered

array([     0,      0,      0,      0,      0,      1,      1,      2,
            0,      1,      4,      3,      4,      4,      9,      8,
            9,     12,     18,     24,     31,     41,     51,     65,
           84,    107,    130,    158,    192,    269,    347,    449,
          550,    735,    926,   1213,   1495,   1872,   2414,   3156,
         3920,   5102,   6329,   8151,  10191,  12953,  16475,  20635,
        25835,  32328,  39815,  49105,  59008,  70879,  82600,  94374,
       105229, 111034, 111966, 103795,  87630,  64131,  37316,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0], dtype=int64)

In [44]:
sum(new)

1185936

In [48]:
salary = 1000000
t = 1
while salary < 1000000000:
    salary *= 2
    t += 1
t

31